FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS builder

WORKDIR /app
COPY . /app

RUN dotnet tool restore

RUN curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > /app/wait_for_it.sh \
    && dotnet cake
