version: '2.0'
services:
  graphdb:
    image: neo4j:3.1.0
    container_name: finance-graphdb
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - /data

  api:
    container_name: finance-api
    build: .
    ports:
      - "5000:5000"
    env_file:
      - api.env
    depends_on:
      - graphdb