FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS builder

# install cakebuild 0.33.0
RUN dotnet tool install --global Cake.Tool --version 0.33.0
ENV PATH="${PATH}:/root/.dotnet/tools"

COPY . /app
WORKDIR /app

RUN curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > /app/wait_for_it.sh \
    && dotnet cake
