version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: hawk-swagger
    ports:
      - "5001:8080"
    environment:
      API_URL: http://localhost:5000/swagger/v1/swagger.json

  graphdb:
    image: neo4j:3.1.0
    container_name: hawk-graphdb
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
    environment:
      NEO4J_AUTH: neo4j/123456

  api:
    container_name: hawk-api
    build: .
    ports:
      - "5000:5000"
    env_file:
      - api.env
    depends_on:
      - graphdb